--1
SELECT AVG(POWER) AS AVG_POWER, MAX(POWER) AS MAX_POWER, MIN(POWER) AS MIN_POWER
FROM STAND_USER;

--2
SELECT COUNT(PRECISION) AS KNOWN_PRECISION, COUNT(USER_NAME) AS TOTAL_USERS
FROM STAND_USER; 

--3
SELECT ROUND(STDDEV(POWER), 3) AS STDDEV_POWER, ROUND(VARIANCE(POWER), 3) AS VARIANCE_POWER
FROM STAND_USER;

--4
SELECT PRECISION, AVG(POWER) AS AVG_POWER
FROM STAND_USER
WHERE PRECISION IS NOT NULL
GROUP BY PRECISION;

--5
SELECT PRECISION, AVG(POWER) AS AVG_POWER
FROM STAND_USER
WHERE PRECISION IS NOT NULL
GROUP BY PRECISION
HAVING AVG(POWER)>80;

--6 
SELECT USER_NAME, STAND_NAME, POWER-(SELECT AVG(POWER) FROM STAND_USER) AS DIFF_FROM_AVG
FROM STAND_USER;

--7
SELECT ROUND(AVG(POWER), 2) AS ROUNDED_AVG_POWER
FROM STAND_USER;

--8
SELECT PRECISION, SUM(POWER)
FROM STAND_USER
GROUP BY ROLLUP(PRECISION);

--9
SELECT EXTRACT(YEAR FROM debut_date) AS debut_year, precision, SUM(power) AS total_power
FROM stand_user
GROUP BY CUBE(EXTRACT(YEAR FROM debut_date), precision)
ORDER BY debut_year, precision;
