--1
SELECT STAND_NAME, UPPER(STAND_NAME) AS STAND_UPPER, LOWER(STAND_NAME) AS STAND_LOWER, INITCAP(STAND_NAME) AS STAND_TITLE
FROM STAND_USER, DUAL;
 
--2
SELECT USER_NAME, CATCHPHRASE, LENGTH(CATCHPHRASE) AS PHRASE_LENGTH
FROM STAND_USER, DUAL
ORDER BY PHRASE_LENGTH DESC;
 
--3
SELECT STAND_NAME, SUBSTR(STAND_NAME, 0, 8) AS STAND_SHORT
FROM STAND_USER, DUAL;
 
--4 
SELECT stand_name, instr(stand_name, 'World') 
from stand_user;
 
--5
SELECT USER_NAME, LPAD(POWER, 8, '*') AS POWER_BAR
FROM STAND_USER, DUAL;
 
--6
SELECT USER_NAME, POWER, ROUND(POWER,-2) AS ROUNDED_POWER, TRUNC(POWER, -2) AS TRUNCATED_POWER, MOD(POWER, 300) AS POWER_MOD_300
FROM STAND_USER, DUAL;
 
--7
SELECT user_name, NVL(to_char(PRECISION),'Unknown') AS "precision_status" 
from stand_user;
 
--8
SELECT USER_NAME, DEBUT_DATE, NEXT_DAY(ADD_MONTHS(DEBUT_DATE, 6), 'MONDAY') AS TRAINING_REVIEW
FROM STAND_USER, DUAL;
 
--9
SELECT USER_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, DEBUT_DATE),0) AS MONTHS_SINCE_DEBUT
FROM STAND_USER, DUAL;
 
--10
SELECT USER_NAME, STAND_NAME, CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT("USER_NAME", ' wields '), "STAND_NAME"), ' with power '), "POWER"), ', but dreams of '), "POWER"*3 ) AS DREAM_STATEMENT
FROM STAND_USER, DUAL;
 
--11
SELECT STAND_NAME
FROM STAND_USER
WHERE REGEXP_LIKE(STAND_NAME, 'World');
 
--12
select user_name, stand_name, soundex(stand_name) from stand_user order by soundex(stand_name);